### ISSUE TITLE
Hello there can u pls add asian dramas too nd a download option as well in different qualities pls?

### ISSUE THREAD

**Issue by Aruraka** [seph1709/AniPlay#1]

**Comment by seph1709** [comment]
Hello @Aruraka  I'll try adding that in the next update after I upload the project source code

**Comment by Aruraka** [comment]
> Hello @Aruraka I'll try adding that in the next update after I upload the project source code

Thanks so much..do u have discord? So that u can inform me there after ur next update?

**Comment by seph1709** [comment]
> > Hello @Aruraka I'll try adding that in the next update after I upload the project source code
> 
> Thanks so much..do u have discord? So that u can inform me there after ur next update?

sorry I don't have discord I will mention you here If It's done

**Comment by Aruraka** [comment]
> > > Hello @Aruraka I'll try adding that in the next update after I upload the project source code
> > 
> > 
> > Thanks so much..do u have discord? So that u can inform me there after ur next update?
> 
> sorry I don't have discord I will mention you here If It's done

Okay thanks so much
