### ISSUE TITLE
x

### ISSUE THREAD

**Issue by fernan542** [seph1709/AniPlay#3]
- Avoid `ScreenUtil` for better ui-ux design. Avoid direct use ng MediaQuery.  For more info, take time to read this [article](https://notes.tst.sh/flutter/media-query).
https://github.com/seph1709/AniPlay/blob/0ad4906b8c54773532ce83f8a34084f8454b1c06/lib/main.dart#L20
https://github.com/seph1709/AniPlay/blob/0ad4906b8c54773532ce83f8a34084f8454b1c06/lib/views/widgets/app_navigation_bottom.dart#L14

- Sobrang common si MVC approach kay Flutter at ito din ang suggested mostly ng mga Flutter users. Pero pagdating sa folder-structure, iba ang ginagamit kay Flutter. It should be feature per folder. Dahil dadating ang time yung `models`, `views`, at `controllers` mo ay dadami at magiging mahirap ito i-maintain. Here's an [example](https://codewithandrea.com/articles/flutter-project-structure/) with explanation.

- Hindi dapat ganto ang pag-access mo sa Theme. Masyadong manual dahil need mo pa i-validate kung naka Dark mode si user. Instead, gumawa ka ng isang theme configuration file na pwede mong tawagin sa `MaterialApp`.

https://github.com/seph1709/AniPlay/blob/0ad4906b8c54773532ce83f8a34084f8454b1c06/lib/views/widgets/app_navigation_bottom.dart#L61

- This will shake the whole tree on every update. Though minor optimization sya, pero pag lumaki na yung data na ginagamit mo mapapansin mo.

https://github.com/seph1709/AniPlay/blob/0ad4906b8c54773532ce83f8a34084f8454b1c06/lib/app.dart#L29C29-L29C46

- Dapat ang laman lang ng controller ay specific sa business logics. You should try to avoid adding Widgets sa loob ng controllers. Separation of concerns per layer. Kung sa presentation(ui) layer lang sya, dapat sa kanya lang sya. Dapat yung mismong page index(int) lang ang ilagay mo, hindi yung `PageController` mismo.

https://github.com/seph1709/AniPlay/blob/0ad4906b8c54773532ce83f8a34084f8454b1c06/lib/controllers/catalog_controller.dart#L16C23-L16C37

I'll add more if I will have extra time.

**Comment by seph1709** [comment]
salamattt sir @fernan542 sa napaka informative na suggestions.. aaralin ko po lahat ng mga sinabi nyo and iaapply sa code I'm happy to welcome para sa mga karagdagan pang suggestion.. God bless po
